server:
  port: 9002


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/


spring:
  application:
    name: open-mall-gateway-admin

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
