spring:
  application:
    name: open-mall-gateway-admin

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  profiles:
    active: @boot.profile@
