spring:
  application:
    name: open-mall-order

  profiles:
    active: @boot.profile@

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.openmall.order.domain

spring.resources.static-locations: classpath:static/,file:static/
